version: 2.1
jobs:
  build:
    docker:
     - image: circleci/python:3.6-jessie-browsers
    steps:
     - add_ssh_keys:
        fingerprints:
         - "bf:35:b9:e8:23:c8:a6:a6:87:a9:ee:de:67:a4:9c:95"
     - checkout
     - run:
        name: Pip install
        # This is using sudo, because this is a test environment. Don't do that on your computer.
        command: sudo pip install -r docs/requirements.txt
     - run:
        name: mkdocs build
        command: mkdocs build --clean --strict
     - deploy:
        name: mkdocs deploy
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
          mkdocs gh-deploy --message "[ci skip] Deployed {sha} with CircleCI and MkDocs version: {version}"
          fi
